apiVersion: apps/v1
kind: Deployment
metadata:
  name: olgaoj-artemis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olgaoj-artemis
  template:
    metadata:
      labels:
        app: olgaoj-artemis
    spec:
      containers:
      - name: olgaoj-artemis
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
